# Generated by Django 2.2.1 on 2020-05-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户端IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='User-Agent')),
                ('authorization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authorization')),
                ('unit_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='梯号')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
            ],
        ),
    ]
