# Generated by Django 2.2.1 on 2020-05-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSBCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, max_length=10, verbose_name='梯号')),
                ('tsb_regcode', models.CharField(blank=True, max_length=20, verbose_name='TSB电梯识别码')),
                ('unit_regcode', models.CharField(blank=True, max_length=50, verbose_name='设备注册代码')),
                ('branch', models.IntegerField(blank=True, choices=[(1, 'oe'), (2, 'ocl')], null=True, verbose_name='分公司')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TSB_elevator_management.TSBCity', verbose_name='城市')),
            ],
        ),
    ]
